@startuml

 Abstract Class Dier {
	+ string Naam
	+ int AantalLedematen
}

Interface IDierBasisPropsWritable {
	+ int AantalLedematen {set;}
	+ string Naam {set;}
}

Interface IDierBasisPropsReadable {
	+ int AantalLedematen {get;}
	+ string Naam {get;}
}

Class Tijger {
}

Class Vis {
}

Class Vogel {
}

Class Jungle {
	+ List<Tijger> Tijgers
}

Class Aquarium {
	+ List<Vis> Vissen
}

Class Vogelkooi {
	+ List<Vogel> Vogels
}

Class Dierentuin {
	+ Jungle JungleZone
	+ Aquarium AquariumZone
	+ Vogelkooi VogelkooiZone
}

Tijger --> Dier : is een
Vis --> Dier : is een
Vogel --> Dier : is een

Dier ..> IDierBasisPropsWritable : implementeert
Dier ..> IDierBasisPropsReadable : implementeert

Jungle o-- Tijger : bevat
Vogelkooi o-- Vogel : bevat
Aquarium o-- Vis : bevat

Dierentuin *-- Jungle : bestaat uit
Dierentuin *-- Aquarium : bestaat uit
Dierentuin *-- Vogelkooi : bestaat uit

@enduml